repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.3
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
          - --args=-write=true

      - id: terraform_validate
        args:
          - --args=-json
        exclude: ^units/

      - id: terraform_tflint
        exclude: ^units/

      - id: terraform_trivy
        args:
          - --args=--severity=HIGH,CRITICAL
        exclude: ^units/

      - id: terraform_checkov
        args:
          - --args=--quiet
          - --args=--compact
        exclude: ^units/

      - id: terragrunt_fmt
        exclude: ^units/

  - repo: local
    hooks:
      - id: terragrunt_stack_validate
        name: Terragrunt Stack Validate
        entry: bash -c 'for stack in $(find infrastructure/live -name "terragrunt.stack.hcl" -exec dirname {} \;); do cd "$stack" && mise exec -- terragrunt validate --all; done'
        language: system
        files: terragrunt\.stack\.hcl$
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.1
    hooks:
      - id: gitleaks
        name: Gitleaks
        description: Detect secrets in your data.
        entry: gitleaks protect --staged --verbose
        language: system
        stages: ["pre-commit"]
