[tools]
opentofu = "{{.OpentofuVersion}}"
terragrunt = "{{.TerragruntVersion}}"

pre-commit = "4.2.0"
tflint = "0.58.0"
trivy = "0.64.1"
checkov = "3.2.447"
gitleaks = "8.27.1"

[env]
PROJECT_NAME = "{{.ProjectName}}"
PROJECT_VERSION = "{{.ProjectVersion}}"

[tools.pre-commit]
post_install = "pre-commit install"

TG_PARALLELISM = "5"
